var milestones = 
{ cards: 
   [ { name: '[ISLAND] Miles',
       type: 'b',
       max: 1,
       milestones: 
        [ { requirement: 'Settle on [ISLAND].',
            modi: 'Nook Inc&apos;s',
            noun: 'Patron' } ] },
     { name: 'Angling for Perfection',
       type: 'p',
       max: 5000,
       prefix: 'Collect ',
       suffix: ' fish.',
       milestones: 
        [ { quantity: 10, modi: 'Accomplished', noun: 'Lad or Lass' },
          { quantity: 100, modi: 'Competent', noun: 'Fishing Fan' },
          { quantity: 500, modi: 'Moderate', noun: 'Beach Bum' },
          { quantity: 2000, modi: 'Fierce', noun: 'Fisher' },
          { quantity: 5000,
            modi: 'Battle-Tested',
            noun: 'Catch of the Day' } ] },
     { name: 'Island Icthyologist',
       type: 'p',
       max: 80,
       prefix: 'Unlock ',
       suffix: ' fish entries in the Critterpedia.',
       milestones: 
        [ { quantity: 10, modi: 'Small-Fry', noun: 'Pesca Pro' },
          { quantity: 20, modi: 'Energetic', noun: 'Angler' },
          { quantity: 40, modi: 'Pond-Raised', noun: 'Tropical Fish' },
          { quantity: 60, modi: 'Hooked', noun: 'Reaction' },
          { quantity: 80, modi: 'Pole-Fishing', noun: 'Expert' } ] },
     { name: 'Island Togetherness',
       type: 'p',
       max: 50,
       prefix: 'Talk to your villagers for ',
       suffix: ' day(s).',
       milestones: 
        [ { quantity: 1, modi: 'Unhindered', noun: 'Wallflower' },
          { quantity: 10, modi: 'Unabashedly', noun: 'Shy Kid' },
          { quantity: 20, modi: 'Respected', noun: 'One' },
          { quantity: 30,
            modi: 'Ludicrously Popular',
            noun: '"It" Guy + "It" Girl"' },
          { quantity: 50, modi: 'Natural', noun: 'Heart Stealer' } ] },
     { name: 'You\'ve Got the Bug',
       type: 'p',
       max: 5000,
       prefix: 'Collect ',
       suffix: ' bugs.',
       milestones: 
        [ { quantity: 10, modi: 'Freshly Delivered', noun: 'Egg' },
          { quantity: 100, modi: 'Weak', noun: 'Grub' },
          { quantity: 500, modi: 'Emerging', noun: 'Pupa' },
          { quantity: 2000, modi: 'Soaring', noun: 'Butterfly' },
          { quantity: 5000, modi: 'Complete', noun: 'Metamorphosis' } ] } ] }